In [1]:
from pdstools import TreeAnalysis
import polars as pl

### set folder and file paths

In [2]:
folder_path = "/Users/hasss/dev/bol.com/modelSnapshots/"
model_filename = "Data-Decision-ADM-ModelSnapshot_AdmModelsSnapshot_20230308T113755_GMT/data.json"
plots_folder_path = "/Users/hasss/dev/pega-datascientist-tools/output"
tree_analysis = TreeAnalysis(
    past_n_snapshots='all', 
    compare_first_n_trees=4, 
    folder_path=folder_path,
    model_filename=model_filename,
    plots_folder_path=plots_folder_path
)

In [3]:
df = tree_analysis.get_df()

AGB models found: shape: (2, 1)
┌───────────────────────────────┐
│ Configuration                 │
│ ---                           │
│ cat                           │
╞═══════════════════════════════╡
│ Mobile_Click_Through_Rate_AGB │
│ Web_Click_Through_Rate_AGB    │
└───────────────────────────────┘

100%|██████████| 13/13 [00:08<00:00,  1.58it/s]

Processing for channel: Mobile_Click_Through_Rate_AGB
Comparing snapshots 2023-03-03 06:00:01 and 2023-03-04 06:00:01
Comparing snapshots 2023-03-04 06:00:01 and 2023-03-05 06:00:01
Comparing snapshots 2023-03-05 06:00:01 and 2023-03-06 06:00:01
Comparing snapshots 2023-03-06 06:00:01 and 2023-03-07 06:00:01
Comparing snapshots 2023-03-07 06:00:01 and 2023-03-08 06:00:01
Processing for channel: Web_Click_Through_Rate_AGB
Comparing snapshots 2023-03-03 06:00:01 and 2023-03-04 06:00:01
Comparing snapshots 2023-03-04 06:00:01 and 2023-03-05 06:00:01
Comparing snapshots 2023-03-05 06:00:01 and 2023-03-06 06:00:01
Comparing snapshots 2023-03-06 06:00:01 and 2023-03-07 06:00:01
Comparing snapshots 2023-03-07 06:00:01 and 2023-03-08 06:00:01

In [7]:
df.head().sort(["channel", "snapshot_from", "tree_id"])

shape: (5, 16)
┌─────────────┬────────────┬───────────┬──────────┬───┬────────────┬───────────┬───────┬───────────┐
│ channel     ┆ snapshot_f ┆ snapshot_ ┆ snapshot ┆ … ┆ left_child ┆ right_chi ┆ depth ┆ flag      │
│ ---         ┆ rom        ┆ to        ┆ ---      ┆   ┆ ---        ┆ ld        ┆ ---   ┆ ---       │
│ str         ┆ ---        ┆ ---       ┆ str      ┆   ┆ f64        ┆ ---       ┆ i64   ┆ str       │
│             ┆ str        ┆ str       ┆          ┆   ┆            ┆ f64       ┆       ┆           │
╞═════════════╪════════════╪═══════════╪══════════╪═══╪════════════╪═══════════╪═══════╪═══════════╡
│ Mobile_Clic ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ … ┆ 2.0        ┆ 7.0       ┆ 1     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ … ┆ 2.0        ┆ 5.0       ┆ 1     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ … ┆ 2.0        ┆ 21.0      ┆ 1     ┆ white     │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ … ┆ 2.0        ┆ 37.0      ┆ 1     ┆ white     │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ … ┆ 3.0        ┆ 4.0       ┆ 2     ┆ white     │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
└─────────────┴────────────┴───────────┴──────────┴───┴────────────┴───────────┴───────┴───────────┘

In [11]:
from enum import Enum
CHANGE_TYPES = Enum('ChangeType', ['split_to_prune', 'split_to_split', 'prune_to_split', 'identical'])
print(CHANGE_TYPES.split_to_prune.name)

NODES = Enum('Nodes', ['node1', 'node2'])
print(NODES.node1.name)

split_to_prune
node1

In [12]:
def run_query(query):
    with pl.Config() as cfg:
        cfg.set_fmt_str_lengths(100)
        display(query)

In [13]:

query = (
    df
    .filter(
        (pl.col("change_type") == CHANGE_TYPES.split_to_prune.name) &
        (pl.col("node") == NODES.node1.name)
    )
    .groupby(['channel', 'change_type', 'predictor'])
    .agg(pl.count())
    .select(pl.col('channel', 'change_type', 'predictor', 'count').sort_by("channel", "predictor"))
)
run_query(query)

shape: (27, 4)
┌───────────────────────────────┬────────────────┬─────────────────────────────────────────┬───────┐
│ channel                       ┆ change_type    ┆ predictor                               ┆ count │
│ ---                           ┆ ---            ┆ ---                                     ┆ ---   │
│ str                           ┆ str            ┆ str                                     ┆ u32   │
╞═══════════════════════════════╪════════════════╪═════════════════════════════════════════╪═══════╡
│ Mobile_Click_Through_Rate_AGB ┆ split_to_prune ┆ Customer.BehavioralData.DaysSinceLastVi ┆ 1     │
│                               ┆                ┆ sit                                     ┆       │
│ Mobile_Click_Through_Rate_AGB ┆ split_to_prune ┆ Customer.Consent.HasService             ┆ 1     │
│ Mobile_Click_Through_Rate_AGB ┆ split_to_prune ┆ Customer.FavouriteConsole               ┆ 1     │
│ Mobile_Click_Through_Rate_AGB ┆ split_to_prune ┆ Customer.Is11306CategoryOrderedIn24M    ┆ 1     │
│ …                             ┆ …              ┆ …                                       ┆ …     │
│ Web_Click_Through_Rate_AGB    ┆ split_to_prune ┆ IH.Web.Inbound.Clicked.pxLastOutcomeTim ┆ 1     │
│                               ┆                ┆ e.DaysSince                             ┆       │
│ Web_Click_Through_Rate_AGB    ┆ split_to_prune ┆ IH.Web.Inbound.Clicked.pyHistoricalOutc ┆ 1     │
│                               ┆                ┆ omeCount                                ┆       │
│ Web_Click_Through_Rate_AGB    ┆ split_to_prune ┆ IH.Web.Inbound.Impression.pxLastOutcome ┆ 1     │
│                               ┆                ┆ Time.DaysSince                          ┆       │
│ Web_Click_Through_Rate_AGB    ┆ split_to_prune ┆ pyName                                  ┆ 1     │
└───────────────────────────────┴────────────────┴─────────────────────────────────────────┴───────┘

In [14]:
item = query[13,:]
display(item)

query1 = (
    df.filter(
            (pl.col("node") == NODES.node1.name) &
            (pl.col("channel") == item.select("channel")) &
            (pl.col("change_type") == item.select("change_type")) & 
            (pl.col("predictor") == item.select("predictor"))
        )
)
run_query(query1)

shape: (1, 4)
┌───────────────────────────────┬────────────────┬───────────────────────────────────┬───────┐
│ channel                       ┆ change_type    ┆ predictor                         ┆ count │
│ ---                           ┆ ---            ┆ ---                               ┆ ---   │
│ str                           ┆ str            ┆ str                               ┆ u32   │
╞═══════════════════════════════╪════════════════╪═══════════════════════════════════╪═══════╡
│ Mobile_Click_Through_Rate_AGB ┆ split_to_prune ┆ IH.Mobile.Inbound.Impression.pyH… ┆ 1     │
└───────────────────────────────┴────────────────┴───────────────────────────────────┴───────┘

shape: (1, 16)
┌─────────────┬────────────┬───────────┬──────────┬───┬────────────┬─────────────┬───────┬─────────┐
│ channel     ┆ snapshot_f ┆ snapshot_ ┆ snapshot ┆ … ┆ left_child ┆ right_child ┆ depth ┆ flag    │
│ ---         ┆ rom        ┆ to        ┆ ---      ┆   ┆ ---        ┆ ---         ┆ ---   ┆ ---     │
│ str         ┆ ---        ┆ ---       ┆ str      ┆   ┆ f64        ┆ f64         ┆ i64   ┆ str     │
│             ┆ str        ┆ str       ┆          ┆   ┆            ┆             ┆       ┆         │
╞═════════════╪════════════╪═══════════╪══════════╪═══╪════════════╪═════════════╪═══════╪═════════╡
│ Mobile_Clic ┆ 20230305   ┆ 20230306  ┆ 20230305 ┆ … ┆ 11.0       ┆ 12.0        ┆ 5     ┆ crimson │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆             ┆       ┆         │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆             ┆       ┆         │
└─────────────┴────────────┴───────────┴──────────┴───┴────────────┴─────────────┴───────┴─────────┘

In [25]:
query2 = (
    df
    .filter(
        (pl.col("node") == NODES.node1.name) &
        (pl.col("change_type") != "identical")
    )
    .groupby(['channel', 'change_type', 'predictor', 'depth'])
    .agg(pl.count())
)
run_query(query2)

shape: (77, 5)
┌───────────────────────────────┬────────────────┬─────────────────────────────────┬───────┬───────┐
│ channel                       ┆ change_type    ┆ predictor                       ┆ depth ┆ count │
│ ---                           ┆ ---            ┆ ---                             ┆ ---   ┆ ---   │
│ str                           ┆ str            ┆ str                             ┆ i64   ┆ u32   │
╞═══════════════════════════════╪════════════════╪═════════════════════════════════╪═══════╪═══════╡
│ Mobile_Click_Through_Rate_AGB ┆ split_to_prune ┆ IH.Mobile.Inbound.Clicked.pxLas ┆ 4     ┆ 1     │
│                               ┆                ┆ tOutcomeTime.DaysSince          ┆       ┆       │
│ Web_Click_Through_Rate_AGB    ┆ split_to_prune ┆ Customer.BehavioralData.L1Shelf ┆ 4     ┆ 1     │
│                               ┆                ┆ VisitMostInSession              ┆       ┆       │
│ Mobile_Click_Through_Rate_AGB ┆ split_to_prune ┆ Customer.BehavioralData.DaysSin ┆ 4     ┆ 1     │
│                               ┆                ┆ ceLastVisit                     ┆       ┆       │
│ Mobile_Click_Through_Rate_AGB ┆ split_to_prune ┆ IH.Mobile.Inbound.Impression.py ┆ 5     ┆ 1     │
│                               ┆                ┆ HistoricalOutcomeCount          ┆       ┆       │
│ …                             ┆ …              ┆ …                               ┆ …     ┆ …     │
│ Web_Click_Through_Rate_AGB    ┆ split_to_split ┆ Customer.OrderShareL1Beauty     ┆ 2     ┆ 1     │
│ Web_Click_Through_Rate_AGB    ┆ split_to_split ┆ IH.Web.Inbound.Clicked.pxLastOu ┆ 2     ┆ 1     │
│                               ┆                ┆ tcomeTime.DaysSince             ┆       ┆       │
│ Mobile_Click_Through_Rate_AGB ┆ split_to_split ┆ IH.Mobile.Inbound.Clicked.pyHis ┆ 1     ┆ 2     │
│                               ┆                ┆ toricalOutcomeCount             ┆       ┆       │
│ Web_Click_Through_Rate_AGB    ┆ split_to_prune ┆ IH.Web.Inbound.Clicked.pxLastGr ┆ 3     ┆ 1     │
│                               ┆                ┆ oupID                           ┆       ┆       │
└───────────────────────────────┴────────────────┴─────────────────────────────────┴───────┴───────┘

#### query:: average gain of splits that were pruned

In [16]:

query3 = (
    df
    .filter(
        (pl.col("change_type") == CHANGE_TYPES.split_to_prune.name) &
        (pl.col("node") == NODES.node1.name)
    )
    .groupby(['channel'])
    .agg(pl.col("gain").mean())
)
run_query(query3)

shape: (2, 2)
┌───────────────────────────────┬───────────┐
│ channel                       ┆ gain      │
│ ---                           ┆ ---       │
│ str                           ┆ f64       │
╞═══════════════════════════════╪═══════════╡
│ Web_Click_Through_Rate_AGB    ┆ 11.412645 │
│ Mobile_Click_Through_Rate_AGB ┆ 3.323169  │
└───────────────────────────────┴───────────┘

#### query:: average gain of identical

In [17]:
query4 = (
    df
    .filter(
        (pl.col("change_type") == CHANGE_TYPES.identical.name) &
        (pl.col("node") == NODES.node1.name)
    )
    .groupby(['channel'])
    .agg(pl.col("gain").mean())
)
run_query(query4)

shape: (2, 2)
┌───────────────────────────────┬───────────┐
│ channel                       ┆ gain      │
│ ---                           ┆ ---       │
│ str                           ┆ f64       │
╞═══════════════════════════════╪═══════════╡
│ Web_Click_Through_Rate_AGB    ┆ 62.106794 │
│ Mobile_Click_Through_Rate_AGB ┆ 48.598743 │
└───────────────────────────────┴───────────┘

#### query:: avg gain of prune to split

In [18]:
q1 = (
    df
    .filter(
        (pl.col("change_type") == CHANGE_TYPES.prune_to_split.name) &
        (pl.col("node") == NODES.node1.name) &
        (pl.col("tree_id") == "tree1")
        # (pl.col("snapshot") == )
    )
    .groupby(['channel'])
    .agg(pl.col("gain").mean())
)
q2 = (
    df
    .filter(
        (pl.col("change_type") == CHANGE_TYPES.prune_to_split.name) &
        (pl.col("node") == NODES.node2.name) &
        (pl.col("tree_id") == "tree1")
    )
    .groupby(['channel'])
    .agg(pl.col("gain").mean())
    .rename({
        "gain": "gain_"
    })
)


run_query(q1.join(q2, on="channel"))

shape: (2, 3)
┌───────────────────────────────┬──────┬──────────┐
│ channel                       ┆ gain ┆ gain_    │
│ ---                           ┆ ---  ┆ ---      │
│ str                           ┆ f64  ┆ f64      │
╞═══════════════════════════════╪══════╪══════════╡
│ Mobile_Click_Through_Rate_AGB ┆ 0.0  ┆ 2.469273 │
│ Web_Click_Through_Rate_AGB    ┆ 0.0  ┆ 2.429723 │
└───────────────────────────────┴──────┴──────────┘

#### query:: split to split

In [19]:
q11 = (
    df
    .filter(
        (pl.col("change_type") == CHANGE_TYPES.split_to_split.name) &
        (pl.col("node") == NODES.node1.name) &
        (pl.col("tree_id") == "tree1")
    )
    .groupby(['channel', 'node'])
    .agg(pl.col("gain").mean())
)
q12 = (
    df
    .filter(
        (pl.col("change_type") == CHANGE_TYPES.split_to_split.name) &
        (pl.col("node") == NODES.node2.name) &
        (pl.col("tree_id") == "tree1")
    )
    .groupby(['channel', "node"])
    .agg(pl.col("gain").mean())
    .rename({
        "gain": "gain_"
    })
)


run_query(q11.join(q12, on="channel"))

shape: (2, 5)
┌───────────────────────────────┬───────┬────────────┬────────────┬───────────┐
│ channel                       ┆ node  ┆ gain       ┆ node_right ┆ gain_     │
│ ---                           ┆ ---   ┆ ---        ┆ ---        ┆ ---       │
│ str                           ┆ str   ┆ f64        ┆ str        ┆ f64       │
╞═══════════════════════════════╪═══════╪════════════╪════════════╪═══════════╡
│ Web_Click_Through_Rate_AGB    ┆ node1 ┆ 13.883167  ┆ node2      ┆ 20.762109 │
│ Mobile_Click_Through_Rate_AGB ┆ node1 ┆ 111.090613 ┆ node2      ┆ 47.243708 │
└───────────────────────────────┴───────┴────────────┴────────────┴───────────┘

In [20]:
qq = (
    df
    .filter(
        (pl.col("change_type") == CHANGE_TYPES.split_to_split.name) &
        (pl.col("tree_id") == "tree1") &
        (pl.col("channel") == "Mobile_Click_Through_Rate_AGB")
    )
    .sort(["snapshot", "depth", "node"])
)
run_query(qq)

shape: (8, 16)
┌─────────────┬────────────┬───────────┬──────────┬───┬────────────┬───────────┬───────┬───────────┐
│ channel     ┆ snapshot_f ┆ snapshot_ ┆ snapshot ┆ … ┆ left_child ┆ right_chi ┆ depth ┆ flag      │
│ ---         ┆ rom        ┆ to        ┆ ---      ┆   ┆ ---        ┆ ld        ┆ ---   ┆ ---       │
│ str         ┆ ---        ┆ ---       ┆ str      ┆   ┆ f64        ┆ ---       ┆ i64   ┆ str       │
│             ┆ str        ┆ str       ┆          ┆   ┆            ┆ f64       ┆       ┆           │
╞═════════════╪════════════╪═══════════╪══════════╪═══╪════════════╪═══════════╪═══════╪═══════════╡
│ Mobile_Clic ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ … ┆ 2.0        ┆ 7.0       ┆ 1     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ … ┆ 2.0        ┆ 5.0       ┆ 1     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230304   ┆ 20230305  ┆ 20230304 ┆ … ┆ 2.0        ┆ 5.0       ┆ 1     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230304   ┆ 20230305  ┆ 20230304 ┆ … ┆ 2.0        ┆ 13.0      ┆ 1     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230305   ┆ 20230306  ┆ 20230305 ┆ … ┆ 15.0       ┆ 16.0      ┆ 3     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230305   ┆ 20230306  ┆ 20230305 ┆ … ┆ 21.0       ┆ 22.0      ┆ 3     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230306   ┆ 20230307  ┆ 20230306 ┆ … ┆ 12.0       ┆ 15.0      ┆ 4     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230306   ┆ 20230307  ┆ 20230306 ┆ … ┆ 18.0       ┆ 19.0      ┆ 4     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
└─────────────┴────────────┴───────────┴──────────┴───┴────────────┴───────────┴───────┴───────────┘

In [23]:
qq = (
    df
    .filter(
        (pl.col("change_type") == CHANGE_TYPES.split_to_split.name) &
        (pl.col("tree_id") == "tree1") &
        (pl.col("channel") == "Web_Click_Through_Rate_AGB")
    )
    .sort(["snapshot", "depth", "node"])
)
run_query(qq)

shape: (10, 16)
┌─────────────┬────────────┬───────────┬──────────┬───┬────────────┬───────────┬───────┬───────────┐
│ channel     ┆ snapshot_f ┆ snapshot_ ┆ snapshot ┆ … ┆ left_child ┆ right_chi ┆ depth ┆ flag      │
│ ---         ┆ rom        ┆ to        ┆ ---      ┆   ┆ ---        ┆ ld        ┆ ---   ┆ ---       │
│ str         ┆ ---        ┆ ---       ┆ str      ┆   ┆ f64        ┆ ---       ┆ i64   ┆ str       │
│             ┆ str        ┆ str       ┆          ┆   ┆            ┆ f64       ┆       ┆           │
╞═════════════╪════════════╪═══════════╪══════════╪═══╪════════════╪═══════════╪═══════╪═══════════╡
│ Web_Click_T ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ … ┆ 20.0       ┆ 23.0      ┆ 2     ┆ goldenrod │
│ hrough_Rate ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ _AGB        ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Web_Click_T ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ … ┆ 20.0       ┆ 29.0      ┆ 2     ┆ goldenrod │
│ hrough_Rate ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ _AGB        ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Web_Click_T ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ … ┆ 4.0        ┆ 7.0       ┆ 3     ┆ goldenrod │
│ hrough_Rate ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ _AGB        ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Web_Click_T ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ … ┆ 4.0        ┆ 5.0       ┆ 3     ┆ goldenrod │
│ hrough_Rate ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ _AGB        ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ …           ┆ …          ┆ …         ┆ …        ┆ … ┆ …          ┆ …         ┆ …     ┆ …         │
│ Web_Click_T ┆ 20230306   ┆ 20230307  ┆ 20230306 ┆ … ┆ 4.0        ┆ 9.0       ┆ 3     ┆ goldenrod │
│ hrough_Rate ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ _AGB        ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Web_Click_T ┆ 20230306   ┆ 20230307  ┆ 20230306 ┆ … ┆ 4.0        ┆ 5.0       ┆ 3     ┆ goldenrod │
│ hrough_Rate ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ _AGB        ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Web_Click_T ┆ 20230307   ┆ 20230308  ┆ 20230307 ┆ … ┆ 7.0        ┆ 12.0      ┆ 3     ┆ goldenrod │
│ hrough_Rate ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ _AGB        ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Web_Click_T ┆ 20230307   ┆ 20230308  ┆ 20230307 ┆ … ┆ 7.0        ┆ 8.0       ┆ 3     ┆ goldenrod │
│ hrough_Rate ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ _AGB        ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
└─────────────┴────────────┴───────────┴──────────┴───┴────────────┴───────────┴───────┴───────────┘

In [24]:
qq1 = (
    df
    .filter(
        # (pl.col("change_type") == CHANGE_TYPES.split_to_split.name) &
        (pl.col("tree_id") == "tree1") &
        (pl.col("channel") == "Mobile_Click_Through_Rate_AGB") &
        (pl.col("depth") == 1)
    )
    .sort(["snapshot", "depth", "node"])
)
run_query(qq1)

shape: (10, 16)
┌─────────────┬────────────┬───────────┬──────────┬───┬────────────┬───────────┬───────┬───────────┐
│ channel     ┆ snapshot_f ┆ snapshot_ ┆ snapshot ┆ … ┆ left_child ┆ right_chi ┆ depth ┆ flag      │
│ ---         ┆ rom        ┆ to        ┆ ---      ┆   ┆ ---        ┆ ld        ┆ ---   ┆ ---       │
│ str         ┆ ---        ┆ ---       ┆ str      ┆   ┆ f64        ┆ ---       ┆ i64   ┆ str       │
│             ┆ str        ┆ str       ┆          ┆   ┆            ┆ f64       ┆       ┆           │
╞═════════════╪════════════╪═══════════╪══════════╪═══╪════════════╪═══════════╪═══════╪═══════════╡
│ Mobile_Clic ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ … ┆ 2.0        ┆ 7.0       ┆ 1     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ … ┆ 2.0        ┆ 5.0       ┆ 1     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230304   ┆ 20230305  ┆ 20230304 ┆ … ┆ 2.0        ┆ 5.0       ┆ 1     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230304   ┆ 20230305  ┆ 20230304 ┆ … ┆ 2.0        ┆ 13.0      ┆ 1     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ …           ┆ …          ┆ …         ┆ …        ┆ … ┆ …          ┆ …         ┆ …     ┆ …         │
│ Mobile_Clic ┆ 20230306   ┆ 20230307  ┆ 20230306 ┆ … ┆ 2.0        ┆ 19.0      ┆ 1     ┆ white     │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230306   ┆ 20230307  ┆ 20230306 ┆ … ┆ 2.0        ┆ 21.0      ┆ 1     ┆ white     │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230307   ┆ 20230308  ┆ 20230307 ┆ … ┆ 2.0        ┆ 21.0      ┆ 1     ┆ white     │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230307   ┆ 20230308  ┆ 20230307 ┆ … ┆ 2.0        ┆ 25.0      ┆ 1     ┆ white     │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
└─────────────┴────────────┴───────────┴──────────┴───┴────────────┴───────────┴───────┴───────────┘

In [35]:
qq1 = (
    df
    .filter(
        # (pl.col("change_type") == CHANGE_TYPES.split_to_split.name) &
        (pl.col("tree_id") == "tree1") &
        (pl.col("channel") == "Mobile_Click_Through_Rate_AGB") &
        (pl.col("depth") == 1)
    )
    .sort(["snapshot", "depth", "node"])
)
run_query(qq1)

shape: (10, 16)
┌─────────────┬────────────┬───────────┬──────────┬───┬────────────┬───────────┬───────┬───────────┐
│ channel     ┆ snapshot_f ┆ snapshot_ ┆ snapshot ┆ … ┆ left_child ┆ right_chi ┆ depth ┆ flag      │
│ ---         ┆ rom        ┆ to        ┆ ---      ┆   ┆ ---        ┆ ld        ┆ ---   ┆ ---       │
│ str         ┆ ---        ┆ ---       ┆ str      ┆   ┆ f64        ┆ ---       ┆ i64   ┆ str       │
│             ┆ str        ┆ str       ┆          ┆   ┆            ┆ f64       ┆       ┆           │
╞═════════════╪════════════╪═══════════╪══════════╪═══╪════════════╪═══════════╪═══════╪═══════════╡
│ Mobile_Clic ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ … ┆ 2.0        ┆ 7.0       ┆ 1     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ … ┆ 2.0        ┆ 5.0       ┆ 1     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230304   ┆ 20230305  ┆ 20230304 ┆ … ┆ 2.0        ┆ 5.0       ┆ 1     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230304   ┆ 20230305  ┆ 20230304 ┆ … ┆ 2.0        ┆ 13.0      ┆ 1     ┆ goldenrod │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ …           ┆ …          ┆ …         ┆ …        ┆ … ┆ …          ┆ …         ┆ …     ┆ …         │
│ Mobile_Clic ┆ 20230306   ┆ 20230307  ┆ 20230306 ┆ … ┆ 2.0        ┆ 19.0      ┆ 1     ┆ white     │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230306   ┆ 20230307  ┆ 20230306 ┆ … ┆ 2.0        ┆ 21.0      ┆ 1     ┆ white     │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230307   ┆ 20230308  ┆ 20230307 ┆ … ┆ 2.0        ┆ 21.0      ┆ 1     ┆ white     │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ Mobile_Clic ┆ 20230307   ┆ 20230308  ┆ 20230307 ┆ … ┆ 2.0        ┆ 25.0      ┆ 1     ┆ white     │
│ k_Through_R ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
│ ate_AGB     ┆            ┆           ┆          ┆   ┆            ┆           ┆       ┆           │
└─────────────┴────────────┴───────────┴──────────┴───┴────────────┴───────────┴───────┴───────────┘